### PR TITLE
Version upgrade

### PR DESCRIPTION
**Pull request by ricky641b**
Updated README as I forgot to upgrade and push the tagged version. If we don't tag the new version then the users won't be able to get the latest version via their Dependency Manager. 

@PiXeL16 Please review this

### CODE REVIEW

**Comment by ricky641b** [comment]
@PiXeL16 Can you please upgrade the version of this repo, I tried to push the tags but don't think it's showing. I am not sure why.

**Comment by ricky641b** [comment]
@PiXeL16 Please check if you can upgrade and tag the latest version to 1.3.1 or 1.3.2, whatever works.

**Comment by ricky641b** [comment]
@PiXeL16 Hi, please add and push a new tag with the new version? as I am not able to take the latest pull via SPM even after the changes are merged. It's a release blocker for one of the app that I am using.

**Comment by PiXeL16** [comment]
Hey @ricky641b Done. Sorry, but I just get to work with OS on the weekend. Also just made you Repo collaborator, so you can do this next time on your own. Thank you for the contributions!

**Pull request merged**
